name: CI/CD for Parent Teacher App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # 🧠 Backend
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Run Backend Tests
        run: |
          cd backend
          npm test || echo "No backend tests found"

      # 🎨 Frontend
      - name: Install Frontend Dependencies
        run: |
          cd parent-teacher-app
          npm install

      - name: Build Frontend
        run: |
          cd parent-teacher-app
          npm run build
